version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_forTx
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=txtxgogo

  shelflayoutmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelflayoutmanager-api
    depends_on:
      - mongodb
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongodb_data: